### ISSUE TITLE
wrong image published

### ISSUE THREAD

**Issue by marinkobabic** [walt-id/waltid-web-wallet#68]
When looking into the code, wallet-backend is the kotlin application. But when I'm looking at the published image, it seems to be a node application

https://hub.docker.com/layers/waltid/wallet-backend/latest/images/sha256-4e8ecfc6b10d3d09bec6d99b859d35775fa5b4224bc1f1414784f86dbcd5cd8f?context=explore

**Comment by mikeplotean** [comment]
thank you for reporting that, should be fixed now.
