### ISSUE TITLE
source code - location

### ISSUE THREAD

**Issue by marinkobabic** [walt-id/waltid-web-wallet#71]
Please can you tell me where I can find the source of the following components

**Portal:**
  waltid/portal:latest
  https://github.com/walt-id/waltid-web-wallet/blob/main/docker-compose/docker-compose.yaml#L20

**VC Repository:**
  waltid/vc-repository:latest
  https://github.com/walt-id/waltid-web-wallet/blob/main/docker-compose/docker-compose.yaml#L27

**Comment by marinkobabic** [comment]
Any chance to get the link to the source code?

**Comment by marinkobabic** [comment]
Can I expect any feedback here or can I close the issue?

**Comment by taminobaumann** [comment]
Answer: https://github.com/walt-id/waltid-identity/issues/39
