### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by inlorite** [walt-id/waltid-web-wallet#75]
Hi,
Issuing credentials worked fine until yesterday when this error `Application error: a client-side exception has occurred (see the browser console for more information).` started happening. I've tried many different things (re-deploying, clearing cookies, switching browsers, using the public wallet, etc) to solve the probem but none of them have worked so far. Is this a known issue?
Thanks in advance.

**Comment by taminobaumann** [comment]
Hey @inlorite, 

thanks for reaching out. I've just issued myself a credential from the [walt.id portal](https://portal.walt.id/) to the [web-wallet](https://wallet.walt.id/). Could you please clarify, who was the issuer of the credential and did you use the deployed version of our wallet or did you run it locally?
